language: java
install: true
script:
  - mvn -s settings.xml -Pprepare-release -Drelease.version.postfix=-${TRAVIS_BUILD_NUMBER}
  - mvn -s settings.xml -Prelease
  - eval $(echo 'MAVEN_VERSION=${project.version}' | mvn -s settings.xml help:evaluate | grep ^MAVEN_VERSION=)
  - git config user.name 'Travis CI'
  - git config user.email 'builds@travis-ci.com'
  - git commit -am "Release v${MAVEN_VERSION}"
  - git tag v${MAVEN_VERSION}
  - git remote add origin2 https://${GITHUB_TOKEN}@github.com/KokaLabs/koka-corporate.git
  - git push origin2 v${MAVEN_VERSION}
env:
  global:
    - secure: 'S3wnCFEK+ibZTe9/fRGiqsll/41j+AgsWhp4omY/XvmUFP5gnQVKqUyPu5QTdHyAUnNcVljiuwSTTH4f7ZSGs0ehYa+r3YbbwxGxbY8wRKYijkAx0NWzMeou6uBajJUj8au5RfAq3E7YCNWLrvDoylDTUxM5KMUSsPSlF6KfmcI='
    - secure: 'chT9GyTqiSlUi79t45b4gw0dMORmhbv+d3pgS6EE8RODQ3R5YjaAHRe/Wjboo1kYa5IXrmnTkUzSN6vEaICxoj6TzrIkVAMoifAMt5ZjCrjKRvRN/ba2JZQslPrskKpgoAOtqFu72oTziXpWhTDEAGX0yDXuwxdEYcRmfq7VJOI='
    - secure: 'ga0mok1OeDk+s6hbTl4awAWBBgX/UXngXQ2WWiVbH2VcR5Ke4EAVrPwabNwesceTb/KJ5ExfoyIK/TPpVmD1mbOr6UT8a/6Ob37U1b4FxpYwa9GD3TsBC55DUau4psEVqwC3V9JejEd5rigHraMzdzNDk4KOIVGDqU0JBM1jNcI='
branches:
  only: master
