language: java
install: true
script:
  - mvn -s settings.xml -Pprepare-release -Drelease.version.postfix=-${TRAVIS_BUILD_NUMBER}
  - mvn -s settings.xml -Prelease
  - eval $(echo 'MAVEN_VERSION=${project.version}' | mvn -s settings.xml help:evaluate | grep ^MAVEN_VERSION=)
  - git config user.name 'Travis CI'
  - git config user.email 'builds@travis-ci.com'
  - git commit -am "Release v${MAVEN_VERSION}"
  - git tag v${MAVEN_VERSION}
  - git push https://${GITHUB_TOKEN}@github.com/KokaLabs/koka-corporate.git v${MAVEN_VERSION} | sed "s/${GITHUB_TOKEN}/[secure]/g"
env:
  global:
    - secure: 'S3wnCFEK+ibZTe9/fRGiqsll/41j+AgsWhp4omY/XvmUFP5gnQVKqUyPu5QTdHyAUnNcVljiuwSTTH4f7ZSGs0ehYa+r3YbbwxGxbY8wRKYijkAx0NWzMeou6uBajJUj8au5RfAq3E7YCNWLrvDoylDTUxM5KMUSsPSlF6KfmcI='
    - secure: 'chT9GyTqiSlUi79t45b4gw0dMORmhbv+d3pgS6EE8RODQ3R5YjaAHRe/Wjboo1kYa5IXrmnTkUzSN6vEaICxoj6TzrIkVAMoifAMt5ZjCrjKRvRN/ba2JZQslPrskKpgoAOtqFu72oTziXpWhTDEAGX0yDXuwxdEYcRmfq7VJOI='
    - secure: 'lpDHPhau9HcEQSb+NIiLZqB5AKVDGjaeQ0uKLV4QxBcrGtatJbL/HVGhupUZiJJjLRIWdq/eFI0aA3l38vZYLBf0UeXphNSqESlBvZh6pgGi2ao4qpv7rwsOD6ZLxVqMaVM/7JER0nYYWXDjmPsJV3VSooURkyA+1FB8xlixnnA='
branches:
  only: master
